
services:
  db:
    image: mysql:8.0
    container_name: mantenedor_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mantenedor
    ports:
      - "3307:3306"  # MySQL corriendo en el puerto 3307
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    networks:
      - api-network

  api:
    build: .
    container_name: mantenimiento_api
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mantenedor?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Lima
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    ports:
      - "3003:3003"  # API corriendo en el puerto 3003
    depends_on:
      - db
    entrypoint: ["./wait-for-it.sh", "db", "3306", "--", "java", "-jar", "app.jar"]
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
